require'mappings'
require'textobjs'

require'plugins.ack'
require'plugins.ale'
require'plugins.coc'
require'plugins.fern'
require'plugins.fugitive'
require'plugins.test'
require'plugins.treesitter'
require'plugins.ultisnips'
