# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

# custom configs
[[manager.prepend_keymap]]
on = [ "g", "c" ]
run = "cd ~/dotfiles/.config"
desc = "Go to the dotfiles directory"

[[manager.prepend_keymap]]
on = [ "g", "o" ]
run = "cd ~/OneDrive\\ -\\ Pontal\\ Brazil"
desc = "Go to the OneDrive directory"

[[manager.prepend_keymap]]
on = [ "g", "t" ]
run = "cd ~/OneDrive\\ -\\ Pontal\\ Brazil/Translation\\ Docs/classified"
desc = "Go to the OneDrive directory"

# { on = [ "g", "o" ],       run = 'cd ~/OneDrive - Pontal Brazil',     desc = "Go to the OneDrive directory" },
# { on = [ "g", "w" ],       run = "cd ~/dev",     desc = "Go to the OneDrive directory" },


# relative jump plugin
[[manager.prepend_keymap]]
on = [ "1" ]
run = "plugin relative-motions --args=1"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "2" ]
run = "plugin relative-motions --args=2"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "3" ]
run = "plugin relative-motions --args=3"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "4" ]
run = "plugin relative-motions --args=4"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "5" ]
run = "plugin relative-motions --args=5"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "6" ]
run = "plugin relative-motions --args=6"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "7" ]
run = "plugin relative-motions --args=7"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "8" ]
run = "plugin relative-motions --args=8"
desc = "Move in relative steps"

[[manager.prepend_keymap]]
on = [ "9" ]
run = "plugin relative-motions --args=9"
desc = "Move in relative steps"
